config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#index"
  resources :categories, only: [:show]
  resources :products, only: [:show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
	has_attached_file :image,
		styles: { :original => "600x600#", :medium => "300x300#", :thumb => "100x100>" }
	validates_attachment :image,
    content_type: {
      content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :list_category

  def list_category
  	@categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(id: params[:id])
    @products = @category.products
    render "home/index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.haml
show.html.haml

app/views/home/index.html.haml
.product-item.col-sm-12.col-md-12
  - @products.each do |product|
    .item.col-sm-3.col-md-3
      .product
        = link_to product_path(id: product.id) do
          .image
            = image_tag "http://mydeal.vn/images/uploaded/282x173/b9a3c8e3c410849f0ee00b47092c763c.jpg", width: "100%"
          %h3
            = product.title
        .summary
          .price
            100.000
            %sup Đ
          %button.btn.btn-primary
            Mua ngay

app/views/layouts/application.html.haml
!!!
%html
  %meta{:content => "width=device-width, initial-scale=1.0, user-scalable=no", :name => "viewport"}/
  %head
    %title Mydeal
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      .top
        .container
          .user-bar
            %a{href: ""} Đăng nhập
            %a{href: ""} Đăng ký
    #main-nav
      .container
        .row
          #logo
            %a{href: root_path}
              Favor.vn
          #categories
            %ul
              - @categories.each do |cat|
                = link_to category_path(id: cat.id) do
                  %li{class: ((cat.id == params[:id].to_i)) ? "active" : ""}
                    = cat.name
    #main
      .container
        = yield

app/views/products/show.html.haml
#breadcrumb.wrap-p
  %span#key-1{:itemref => "key-2", :itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
    %a{:href => "http://mydeal.vn", :itemprop => "url"}
      %span{:itemprop => "title", :title => "mydeal.vn"} Trang chủ
     
    = image_tag "icon_arrow_sub.png", :style => "vertical-align:middle"
  %span#key-3{:itemprop => "child", :itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
    %a{:href => "http://mydeal.vn/danh-muc/12/ao-so-mi-nu.html", :itemprop => "url", :title => "Áo sơ mi nữ"}
      %span{:itemprop => "title"} Áo sơ mi nữ
     
    = image_tag "icon_arrow_sub.png", :style => "vertical-align:middle"
  %span Áo denim thêu hoa văn
.product-detail
  .photo-viewer.col-sm-5.col-md-5
    .row
      .photo-holder
        #bigPic
          %img{:alt => "Áo denim thêu hoa văn", :src => "http://mydeal.vn/images/uploaded/434x267/0079ea205138c5feca058077c3942e39.jpg", :style => "display: none; opacity: 1; z-index: 1;", :title => "Áo denim thêu hoa văn"}/
          %img{:alt => "Áo denim thêu hoa văn", :src => "http://mydeal.vn/images/uploaded/434x267/0079ea205138c5feca058077c3942e39.jpg", :style => "display: none; opacity: 1; z-index: 1;", :title => "Áo denim thêu hoa văn"}/
          %img{:alt => "Áo denim thêu hoa văn", :src => "http://mydeal.vn/images/uploaded/434x267/0079ea205138c5feca058077c3942e39.jpg", :style => "display: block; opacity: 1; z-index: 1;", :title => "Áo denim thêu hoa văn"}/
          %img{:alt => "Áo denim thêu hoa văn", :src => "http://mydeal.vn/images/uploaded/434x267/0079ea205138c5feca058077c3942e39.jpg", :style => "display: none; opacity: 1; z-index: 1;", :title => "Áo denim thêu hoa văn"}/
          %img{:alt => "Áo denim thêu hoa văn", :src => "http://mydeal.vn/images/uploaded/434x267/0079ea205138c5feca058077c3942e39.jpg", :style => "display: none; opacity: 1; z-index: 1;", :title => "Áo denim thêu hoa văn"}/
        %ul#thumbs
          %li{:rel => "1"}
            %img{:alt => "", :src => "http://mydeal.vn/images/uploaded/75x46/2ec8077703ac11568a2a11ad9d2b1c71.jpg"}/
          %li{:rel => "2"}
            %img{:alt => "", :src => "http://mydeal.vn/images/uploaded/75x46/fd14701051a30b28f17696b082625052.jpg"}/
          %li.active{:rel => "3"}
            %img{:alt => "", :src => "http://mydeal.vn/images/uploaded/75x46/80505aca74ed0b72b4e89cabbd0cdcf1.jpg"}/
          %li{:rel => "4"}
            %img{:alt => "", :src => "http://mydeal.vn/images/uploaded/75x46/be0b0e4ae0f4b32c8a6177cde43543a2.jpg"}/
      / end slide show image
    .clear
  .product-info.col-sm-7.col-md-7
    .row
      %h1
        Áo vải ren đắt tiền
    .row
      .summary
        Áo khoác dạ form dài viền màu cao cấp Thiết kế sang trọng giúp người mặc tôn lên được vẻ đẹp và đẳng cấp của bản thân. Gía chỉ còn 450.000đ tại mydeal.vn!
    .row
      Chọn màu sắc
      .size-color
        %span
          %img{:height => "48", :src => "http://mydeal.vn/images/uploaded/48x48/397454bb31c17446042bc56e5a4adbce.jpg", :style => "border:1px solid #ccc; padding:2px;", :width => "48"}>/
          Kem - size M
        %span
          450.000
          %sup đ
        %span{:style => "padding-left:10px;"}
          %select.form-control{:name => "qty-1"}
            %option{:value => "0"} 0
            %option{:value => "1"} 1
            %option{:value => "2"} 2
            %option{:value => "3"} 3
            %option{:value => "4"} 4
            %option{:value => "5"} 5
            %option{:value => "6"} 6
      .size-color
        %span
          %img{:height => "48", :src => "http://mydeal.vn/images/uploaded/48x48/397454bb31c17446042bc56e5a4adbce.jpg", :style => "border:1px solid #ccc; padding:2px;", :width => "48"}>/
          Kem - size M
        %span
          450.000
          %sup đ
        %span{:style => "padding-left:10px;"}
          %select.form-control{:name => "qty-1"}
            %option{:value => "0"} 0
            %option{:value => "1"} 1
            %option{:value => "2"} 2
            %option{:value => "3"} 3
            %option{:value => "4"} 4
            %option{:value => "5"} 5
            %option{:value => "6"} 6
    .row
      .price-buy
        .price
          400.000
          %sup đ
        %button.btn.btn-primary.btn-lg
          Mua ngay